/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ShelvesRouteImport } from './routes/shelves'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AuthorNameRouteImport } from './routes/author.$name'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as SettingsKoboRouteImport } from './routes/settings/kobo'
import { Route as ShelvesIndexRouteImport } from './routes/shelves.index'
import { Route as ShelvesShelfIdRouteImport } from './routes/shelves.$shelfId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as BooksBookIdEditRouteImport } from './routes/books.$bookId_.edit'
import { Route as ApiBooksBookIdCoverRouteImport } from './routes/api/books/$bookId/cover'
import { Route as ApiBooksBookIdFilesFileIdRouteImport } from './routes/api/books/$bookId/files/$fileId'
import { Route as ApiKoboTokenV1SplatRouteImport } from './routes/api/kobo/$token/v1/$'
import { Route as ApiKoboTokenV1InitializationRouteImport } from './routes/api/kobo/$token/v1/initialization'
import { Route as ApiKoboTokenDownloadBookIdBookFormatRouteImport } from './routes/api/kobo/$token/download/$bookId/$bookFormat'
import { Route as ApiKoboTokenV1AuthDeviceRouteImport } from './routes/api/kobo/$token/v1/auth/device'
import { Route as ApiKoboTokenV1AuthRefreshRouteImport } from './routes/api/kobo/$token/v1/auth/refresh'
import { Route as ApiKoboTokenV1LibraryBookUuidRouteImport } from './routes/api/kobo/$token/v1/library/$bookUuid'
import { Route as ApiKoboTokenV1LibrarySyncRouteImport } from './routes/api/kobo/$token/v1/library/sync'
import { Route as ApiKoboTokenV1LibraryTagsRouteImport } from './routes/api/kobo/$token/v1/library/tags'
import { Route as ApiKoboTokenV1LibraryIdsMetadataRouteImport } from './routes/api/kobo/$token/v1/library/$ids/metadata'
import { Route as ApiKoboTokenV1LibraryIdsStateRouteImport } from './routes/api/kobo/$token/v1/library/$ids/state'
import { Route as ApiKoboTokenV1LibraryTagsTagIdRouteImport } from './routes/api/kobo/$token/v1/library/tags/$tagId'
import { Route as ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRouteImport } from './routes/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image[.]jpg'
import { Route as ApiKoboTokenV1LibraryTagsTagIdItemsRouteImport } from './routes/api/kobo/$token/v1/library/tags/$tagId/items'
import { Route as ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRouteImport } from './routes/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image[.]jpg'
import { Route as ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRouteImport } from './routes/api/kobo/$token/v1/library/tags/$tagId/items/delete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesRoute = ShelvesRouteImport.update({
  id: '/shelves',
  path: '/shelves',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorNameRoute = AuthorNameRouteImport.update({
  id: '/author/$name',
  path: '/author/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsKoboRoute = SettingsKoboRouteImport.update({
  id: '/settings/kobo',
  path: '/settings/kobo',
  getParentRoute: () => rootRouteImport,
} as any)
const ShelvesIndexRoute = ShelvesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShelvesRoute,
} as any)
const ShelvesShelfIdRoute = ShelvesShelfIdRouteImport.update({
  id: '/$shelfId',
  path: '/$shelfId',
  getParentRoute: () => ShelvesRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdEditRoute = BooksBookIdEditRouteImport.update({
  id: '/books/$bookId_/edit',
  path: '/books/$bookId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksBookIdCoverRoute = ApiBooksBookIdCoverRouteImport.update({
  id: '/api/books/$bookId/cover',
  path: '/api/books/$bookId/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksBookIdFilesFileIdRoute =
  ApiBooksBookIdFilesFileIdRouteImport.update({
    id: '/api/books/$bookId/files/$fileId',
    path: '/api/books/$bookId/files/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1SplatRoute = ApiKoboTokenV1SplatRouteImport.update({
  id: '/api/kobo/$token/v1/$',
  path: '/api/kobo/$token/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKoboTokenV1InitializationRoute =
  ApiKoboTokenV1InitializationRouteImport.update({
    id: '/api/kobo/$token/v1/initialization',
    path: '/api/kobo/$token/v1/initialization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenDownloadBookIdBookFormatRoute =
  ApiKoboTokenDownloadBookIdBookFormatRouteImport.update({
    id: '/api/kobo/$token/download/$bookId/$bookFormat',
    path: '/api/kobo/$token/download/$bookId/$bookFormat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1AuthDeviceRoute =
  ApiKoboTokenV1AuthDeviceRouteImport.update({
    id: '/api/kobo/$token/v1/auth/device',
    path: '/api/kobo/$token/v1/auth/device',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1AuthRefreshRoute =
  ApiKoboTokenV1AuthRefreshRouteImport.update({
    id: '/api/kobo/$token/v1/auth/refresh',
    path: '/api/kobo/$token/v1/auth/refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibraryBookUuidRoute =
  ApiKoboTokenV1LibraryBookUuidRouteImport.update({
    id: '/api/kobo/$token/v1/library/$bookUuid',
    path: '/api/kobo/$token/v1/library/$bookUuid',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibrarySyncRoute =
  ApiKoboTokenV1LibrarySyncRouteImport.update({
    id: '/api/kobo/$token/v1/library/sync',
    path: '/api/kobo/$token/v1/library/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibraryTagsRoute =
  ApiKoboTokenV1LibraryTagsRouteImport.update({
    id: '/api/kobo/$token/v1/library/tags',
    path: '/api/kobo/$token/v1/library/tags',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibraryIdsMetadataRoute =
  ApiKoboTokenV1LibraryIdsMetadataRouteImport.update({
    id: '/api/kobo/$token/v1/library/$ids/metadata',
    path: '/api/kobo/$token/v1/library/$ids/metadata',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibraryIdsStateRoute =
  ApiKoboTokenV1LibraryIdsStateRouteImport.update({
    id: '/api/kobo/$token/v1/library/$ids/state',
    path: '/api/kobo/$token/v1/library/$ids/state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibraryTagsTagIdRoute =
  ApiKoboTokenV1LibraryTagsTagIdRouteImport.update({
    id: '/$tagId',
    path: '/$tagId',
    getParentRoute: () => ApiKoboTokenV1LibraryTagsRoute,
  } as any)
const ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRoute =
  ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRouteImport.update({
    id: '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg',
    path: '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiKoboTokenV1LibraryTagsTagIdItemsRoute =
  ApiKoboTokenV1LibraryTagsTagIdItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => ApiKoboTokenV1LibraryTagsTagIdRoute,
  } as any)
const ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRoute =
  ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRouteImport.update(
    {
      id: '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg',
      path: '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRoute =
  ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => ApiKoboTokenV1LibraryTagsTagIdItemsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/shelves': typeof ShelvesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/author/$name': typeof AuthorNameRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/settings/kobo': typeof SettingsKoboRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
  '/shelves/': typeof ShelvesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/api/books/$bookId/cover': typeof ApiBooksBookIdCoverRoute
  '/api/books/$bookId/files/$fileId': typeof ApiBooksBookIdFilesFileIdRoute
  '/api/kobo/$token/v1/$': typeof ApiKoboTokenV1SplatRoute
  '/api/kobo/$token/v1/initialization': typeof ApiKoboTokenV1InitializationRoute
  '/api/kobo/$token/download/$bookId/$bookFormat': typeof ApiKoboTokenDownloadBookIdBookFormatRoute
  '/api/kobo/$token/v1/auth/device': typeof ApiKoboTokenV1AuthDeviceRoute
  '/api/kobo/$token/v1/auth/refresh': typeof ApiKoboTokenV1AuthRefreshRoute
  '/api/kobo/$token/v1/library/$bookUuid': typeof ApiKoboTokenV1LibraryBookUuidRoute
  '/api/kobo/$token/v1/library/sync': typeof ApiKoboTokenV1LibrarySyncRoute
  '/api/kobo/$token/v1/library/tags': typeof ApiKoboTokenV1LibraryTagsRouteWithChildren
  '/api/kobo/$token/v1/library/$ids/metadata': typeof ApiKoboTokenV1LibraryIdsMetadataRoute
  '/api/kobo/$token/v1/library/$ids/state': typeof ApiKoboTokenV1LibraryIdsStateRoute
  '/api/kobo/$token/v1/library/tags/$tagId': typeof ApiKoboTokenV1LibraryTagsTagIdRouteWithChildren
  '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg': typeof ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRoute
  '/api/kobo/$token/v1/library/tags/$tagId/items': typeof ApiKoboTokenV1LibraryTagsTagIdItemsRouteWithChildren
  '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg': typeof ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRoute
  '/api/kobo/$token/v1/library/tags/$tagId/items/delete': typeof ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/author/$name': typeof AuthorNameRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/settings/kobo': typeof SettingsKoboRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
  '/shelves': typeof ShelvesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/api/books/$bookId/cover': typeof ApiBooksBookIdCoverRoute
  '/api/books/$bookId/files/$fileId': typeof ApiBooksBookIdFilesFileIdRoute
  '/api/kobo/$token/v1/$': typeof ApiKoboTokenV1SplatRoute
  '/api/kobo/$token/v1/initialization': typeof ApiKoboTokenV1InitializationRoute
  '/api/kobo/$token/download/$bookId/$bookFormat': typeof ApiKoboTokenDownloadBookIdBookFormatRoute
  '/api/kobo/$token/v1/auth/device': typeof ApiKoboTokenV1AuthDeviceRoute
  '/api/kobo/$token/v1/auth/refresh': typeof ApiKoboTokenV1AuthRefreshRoute
  '/api/kobo/$token/v1/library/$bookUuid': typeof ApiKoboTokenV1LibraryBookUuidRoute
  '/api/kobo/$token/v1/library/sync': typeof ApiKoboTokenV1LibrarySyncRoute
  '/api/kobo/$token/v1/library/tags': typeof ApiKoboTokenV1LibraryTagsRouteWithChildren
  '/api/kobo/$token/v1/library/$ids/metadata': typeof ApiKoboTokenV1LibraryIdsMetadataRoute
  '/api/kobo/$token/v1/library/$ids/state': typeof ApiKoboTokenV1LibraryIdsStateRoute
  '/api/kobo/$token/v1/library/tags/$tagId': typeof ApiKoboTokenV1LibraryTagsTagIdRouteWithChildren
  '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg': typeof ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRoute
  '/api/kobo/$token/v1/library/tags/$tagId/items': typeof ApiKoboTokenV1LibraryTagsTagIdItemsRouteWithChildren
  '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg': typeof ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRoute
  '/api/kobo/$token/v1/library/tags/$tagId/items/delete': typeof ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/register': typeof RegisterRoute
  '/shelves': typeof ShelvesRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/author/$name': typeof AuthorNameRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/settings/kobo': typeof SettingsKoboRoute
  '/shelves/$shelfId': typeof ShelvesShelfIdRoute
  '/shelves/': typeof ShelvesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/books/$bookId_/edit': typeof BooksBookIdEditRoute
  '/api/books/$bookId/cover': typeof ApiBooksBookIdCoverRoute
  '/api/books/$bookId/files/$fileId': typeof ApiBooksBookIdFilesFileIdRoute
  '/api/kobo/$token/v1/$': typeof ApiKoboTokenV1SplatRoute
  '/api/kobo/$token/v1/initialization': typeof ApiKoboTokenV1InitializationRoute
  '/api/kobo/$token/download/$bookId/$bookFormat': typeof ApiKoboTokenDownloadBookIdBookFormatRoute
  '/api/kobo/$token/v1/auth/device': typeof ApiKoboTokenV1AuthDeviceRoute
  '/api/kobo/$token/v1/auth/refresh': typeof ApiKoboTokenV1AuthRefreshRoute
  '/api/kobo/$token/v1/library/$bookUuid': typeof ApiKoboTokenV1LibraryBookUuidRoute
  '/api/kobo/$token/v1/library/sync': typeof ApiKoboTokenV1LibrarySyncRoute
  '/api/kobo/$token/v1/library/tags': typeof ApiKoboTokenV1LibraryTagsRouteWithChildren
  '/api/kobo/$token/v1/library/$ids/metadata': typeof ApiKoboTokenV1LibraryIdsMetadataRoute
  '/api/kobo/$token/v1/library/$ids/state': typeof ApiKoboTokenV1LibraryIdsStateRoute
  '/api/kobo/$token/v1/library/tags/$tagId': typeof ApiKoboTokenV1LibraryTagsTagIdRouteWithChildren
  '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg': typeof ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRoute
  '/api/kobo/$token/v1/library/tags/$tagId/items': typeof ApiKoboTokenV1LibraryTagsTagIdItemsRouteWithChildren
  '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg': typeof ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRoute
  '/api/kobo/$token/v1/library/tags/$tagId/items/delete': typeof ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/pending-approval'
    | '/register'
    | '/shelves'
    | '/admin/users'
    | '/author/$name'
    | '/books/$bookId'
    | '/settings/kobo'
    | '/shelves/$shelfId'
    | '/shelves/'
    | '/api/auth/$'
    | '/books/$bookId/edit'
    | '/api/books/$bookId/cover'
    | '/api/books/$bookId/files/$fileId'
    | '/api/kobo/$token/v1/$'
    | '/api/kobo/$token/v1/initialization'
    | '/api/kobo/$token/download/$bookId/$bookFormat'
    | '/api/kobo/$token/v1/auth/device'
    | '/api/kobo/$token/v1/auth/refresh'
    | '/api/kobo/$token/v1/library/$bookUuid'
    | '/api/kobo/$token/v1/library/sync'
    | '/api/kobo/$token/v1/library/tags'
    | '/api/kobo/$token/v1/library/$ids/metadata'
    | '/api/kobo/$token/v1/library/$ids/state'
    | '/api/kobo/$token/v1/library/tags/$tagId'
    | '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg'
    | '/api/kobo/$token/v1/library/tags/$tagId/items'
    | '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg'
    | '/api/kobo/$token/v1/library/tags/$tagId/items/delete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/pending-approval'
    | '/register'
    | '/admin/users'
    | '/author/$name'
    | '/books/$bookId'
    | '/settings/kobo'
    | '/shelves/$shelfId'
    | '/shelves'
    | '/api/auth/$'
    | '/books/$bookId/edit'
    | '/api/books/$bookId/cover'
    | '/api/books/$bookId/files/$fileId'
    | '/api/kobo/$token/v1/$'
    | '/api/kobo/$token/v1/initialization'
    | '/api/kobo/$token/download/$bookId/$bookFormat'
    | '/api/kobo/$token/v1/auth/device'
    | '/api/kobo/$token/v1/auth/refresh'
    | '/api/kobo/$token/v1/library/$bookUuid'
    | '/api/kobo/$token/v1/library/sync'
    | '/api/kobo/$token/v1/library/tags'
    | '/api/kobo/$token/v1/library/$ids/metadata'
    | '/api/kobo/$token/v1/library/$ids/state'
    | '/api/kobo/$token/v1/library/tags/$tagId'
    | '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg'
    | '/api/kobo/$token/v1/library/tags/$tagId/items'
    | '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg'
    | '/api/kobo/$token/v1/library/tags/$tagId/items/delete'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/pending-approval'
    | '/register'
    | '/shelves'
    | '/admin/users'
    | '/author/$name'
    | '/books/$bookId'
    | '/settings/kobo'
    | '/shelves/$shelfId'
    | '/shelves/'
    | '/api/auth/$'
    | '/books/$bookId_/edit'
    | '/api/books/$bookId/cover'
    | '/api/books/$bookId/files/$fileId'
    | '/api/kobo/$token/v1/$'
    | '/api/kobo/$token/v1/initialization'
    | '/api/kobo/$token/download/$bookId/$bookFormat'
    | '/api/kobo/$token/v1/auth/device'
    | '/api/kobo/$token/v1/auth/refresh'
    | '/api/kobo/$token/v1/library/$bookUuid'
    | '/api/kobo/$token/v1/library/sync'
    | '/api/kobo/$token/v1/library/tags'
    | '/api/kobo/$token/v1/library/$ids/metadata'
    | '/api/kobo/$token/v1/library/$ids/state'
    | '/api/kobo/$token/v1/library/tags/$tagId'
    | '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg'
    | '/api/kobo/$token/v1/library/tags/$tagId/items'
    | '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg'
    | '/api/kobo/$token/v1/library/tags/$tagId/items/delete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  RegisterRoute: typeof RegisterRoute
  ShelvesRoute: typeof ShelvesRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AuthorNameRoute: typeof AuthorNameRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  SettingsKoboRoute: typeof SettingsKoboRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  BooksBookIdEditRoute: typeof BooksBookIdEditRoute
  ApiBooksBookIdCoverRoute: typeof ApiBooksBookIdCoverRoute
  ApiBooksBookIdFilesFileIdRoute: typeof ApiBooksBookIdFilesFileIdRoute
  ApiKoboTokenV1SplatRoute: typeof ApiKoboTokenV1SplatRoute
  ApiKoboTokenV1InitializationRoute: typeof ApiKoboTokenV1InitializationRoute
  ApiKoboTokenDownloadBookIdBookFormatRoute: typeof ApiKoboTokenDownloadBookIdBookFormatRoute
  ApiKoboTokenV1AuthDeviceRoute: typeof ApiKoboTokenV1AuthDeviceRoute
  ApiKoboTokenV1AuthRefreshRoute: typeof ApiKoboTokenV1AuthRefreshRoute
  ApiKoboTokenV1LibraryBookUuidRoute: typeof ApiKoboTokenV1LibraryBookUuidRoute
  ApiKoboTokenV1LibrarySyncRoute: typeof ApiKoboTokenV1LibrarySyncRoute
  ApiKoboTokenV1LibraryTagsRoute: typeof ApiKoboTokenV1LibraryTagsRouteWithChildren
  ApiKoboTokenV1LibraryIdsMetadataRoute: typeof ApiKoboTokenV1LibraryIdsMetadataRoute
  ApiKoboTokenV1LibraryIdsStateRoute: typeof ApiKoboTokenV1LibraryIdsStateRoute
  ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRoute: typeof ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRoute
  ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRoute: typeof ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves': {
      id: '/shelves'
      path: '/shelves'
      fullPath: '/shelves'
      preLoaderRoute: typeof ShelvesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$name': {
      id: '/author/$name'
      path: '/author/$name'
      fullPath: '/author/$name'
      preLoaderRoute: typeof AuthorNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/kobo': {
      id: '/settings/kobo'
      path: '/settings/kobo'
      fullPath: '/settings/kobo'
      preLoaderRoute: typeof SettingsKoboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelves/': {
      id: '/shelves/'
      path: '/'
      fullPath: '/shelves/'
      preLoaderRoute: typeof ShelvesIndexRouteImport
      parentRoute: typeof ShelvesRoute
    }
    '/shelves/$shelfId': {
      id: '/shelves/$shelfId'
      path: '/$shelfId'
      fullPath: '/shelves/$shelfId'
      preLoaderRoute: typeof ShelvesShelfIdRouteImport
      parentRoute: typeof ShelvesRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId_/edit': {
      id: '/books/$bookId_/edit'
      path: '/books/$bookId/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof BooksBookIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$bookId/cover': {
      id: '/api/books/$bookId/cover'
      path: '/api/books/$bookId/cover'
      fullPath: '/api/books/$bookId/cover'
      preLoaderRoute: typeof ApiBooksBookIdCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$bookId/files/$fileId': {
      id: '/api/books/$bookId/files/$fileId'
      path: '/api/books/$bookId/files/$fileId'
      fullPath: '/api/books/$bookId/files/$fileId'
      preLoaderRoute: typeof ApiBooksBookIdFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/$': {
      id: '/api/kobo/$token/v1/$'
      path: '/api/kobo/$token/v1/$'
      fullPath: '/api/kobo/$token/v1/$'
      preLoaderRoute: typeof ApiKoboTokenV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/initialization': {
      id: '/api/kobo/$token/v1/initialization'
      path: '/api/kobo/$token/v1/initialization'
      fullPath: '/api/kobo/$token/v1/initialization'
      preLoaderRoute: typeof ApiKoboTokenV1InitializationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/download/$bookId/$bookFormat': {
      id: '/api/kobo/$token/download/$bookId/$bookFormat'
      path: '/api/kobo/$token/download/$bookId/$bookFormat'
      fullPath: '/api/kobo/$token/download/$bookId/$bookFormat'
      preLoaderRoute: typeof ApiKoboTokenDownloadBookIdBookFormatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/auth/device': {
      id: '/api/kobo/$token/v1/auth/device'
      path: '/api/kobo/$token/v1/auth/device'
      fullPath: '/api/kobo/$token/v1/auth/device'
      preLoaderRoute: typeof ApiKoboTokenV1AuthDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/auth/refresh': {
      id: '/api/kobo/$token/v1/auth/refresh'
      path: '/api/kobo/$token/v1/auth/refresh'
      fullPath: '/api/kobo/$token/v1/auth/refresh'
      preLoaderRoute: typeof ApiKoboTokenV1AuthRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/$bookUuid': {
      id: '/api/kobo/$token/v1/library/$bookUuid'
      path: '/api/kobo/$token/v1/library/$bookUuid'
      fullPath: '/api/kobo/$token/v1/library/$bookUuid'
      preLoaderRoute: typeof ApiKoboTokenV1LibraryBookUuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/sync': {
      id: '/api/kobo/$token/v1/library/sync'
      path: '/api/kobo/$token/v1/library/sync'
      fullPath: '/api/kobo/$token/v1/library/sync'
      preLoaderRoute: typeof ApiKoboTokenV1LibrarySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/tags': {
      id: '/api/kobo/$token/v1/library/tags'
      path: '/api/kobo/$token/v1/library/tags'
      fullPath: '/api/kobo/$token/v1/library/tags'
      preLoaderRoute: typeof ApiKoboTokenV1LibraryTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/$ids/metadata': {
      id: '/api/kobo/$token/v1/library/$ids/metadata'
      path: '/api/kobo/$token/v1/library/$ids/metadata'
      fullPath: '/api/kobo/$token/v1/library/$ids/metadata'
      preLoaderRoute: typeof ApiKoboTokenV1LibraryIdsMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/$ids/state': {
      id: '/api/kobo/$token/v1/library/$ids/state'
      path: '/api/kobo/$token/v1/library/$ids/state'
      fullPath: '/api/kobo/$token/v1/library/$ids/state'
      preLoaderRoute: typeof ApiKoboTokenV1LibraryIdsStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/tags/$tagId': {
      id: '/api/kobo/$token/v1/library/tags/$tagId'
      path: '/$tagId'
      fullPath: '/api/kobo/$token/v1/library/tags/$tagId'
      preLoaderRoute: typeof ApiKoboTokenV1LibraryTagsTagIdRouteImport
      parentRoute: typeof ApiKoboTokenV1LibraryTagsRoute
    }
    '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg': {
      id: '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg'
      path: '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg'
      fullPath: '/api/kobo/$token/$imageId/$width/$height/$isGreyscale/image.jpg'
      preLoaderRoute: typeof ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/tags/$tagId/items': {
      id: '/api/kobo/$token/v1/library/tags/$tagId/items'
      path: '/items'
      fullPath: '/api/kobo/$token/v1/library/tags/$tagId/items'
      preLoaderRoute: typeof ApiKoboTokenV1LibraryTagsTagIdItemsRouteImport
      parentRoute: typeof ApiKoboTokenV1LibraryTagsTagIdRoute
    }
    '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg': {
      id: '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg'
      path: '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg'
      fullPath: '/api/kobo/$token/$imageId/$width/$height/$quality/$isGreyscale/image.jpg'
      preLoaderRoute: typeof ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kobo/$token/v1/library/tags/$tagId/items/delete': {
      id: '/api/kobo/$token/v1/library/tags/$tagId/items/delete'
      path: '/delete'
      fullPath: '/api/kobo/$token/v1/library/tags/$tagId/items/delete'
      preLoaderRoute: typeof ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRouteImport
      parentRoute: typeof ApiKoboTokenV1LibraryTagsTagIdItemsRoute
    }
  }
}

interface ShelvesRouteChildren {
  ShelvesShelfIdRoute: typeof ShelvesShelfIdRoute
  ShelvesIndexRoute: typeof ShelvesIndexRoute
}

const ShelvesRouteChildren: ShelvesRouteChildren = {
  ShelvesShelfIdRoute: ShelvesShelfIdRoute,
  ShelvesIndexRoute: ShelvesIndexRoute,
}

const ShelvesRouteWithChildren =
  ShelvesRoute._addFileChildren(ShelvesRouteChildren)

interface ApiKoboTokenV1LibraryTagsTagIdItemsRouteChildren {
  ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRoute: typeof ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRoute
}

const ApiKoboTokenV1LibraryTagsTagIdItemsRouteChildren: ApiKoboTokenV1LibraryTagsTagIdItemsRouteChildren =
  {
    ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRoute:
      ApiKoboTokenV1LibraryTagsTagIdItemsDeleteRoute,
  }

const ApiKoboTokenV1LibraryTagsTagIdItemsRouteWithChildren =
  ApiKoboTokenV1LibraryTagsTagIdItemsRoute._addFileChildren(
    ApiKoboTokenV1LibraryTagsTagIdItemsRouteChildren,
  )

interface ApiKoboTokenV1LibraryTagsTagIdRouteChildren {
  ApiKoboTokenV1LibraryTagsTagIdItemsRoute: typeof ApiKoboTokenV1LibraryTagsTagIdItemsRouteWithChildren
}

const ApiKoboTokenV1LibraryTagsTagIdRouteChildren: ApiKoboTokenV1LibraryTagsTagIdRouteChildren =
  {
    ApiKoboTokenV1LibraryTagsTagIdItemsRoute:
      ApiKoboTokenV1LibraryTagsTagIdItemsRouteWithChildren,
  }

const ApiKoboTokenV1LibraryTagsTagIdRouteWithChildren =
  ApiKoboTokenV1LibraryTagsTagIdRoute._addFileChildren(
    ApiKoboTokenV1LibraryTagsTagIdRouteChildren,
  )

interface ApiKoboTokenV1LibraryTagsRouteChildren {
  ApiKoboTokenV1LibraryTagsTagIdRoute: typeof ApiKoboTokenV1LibraryTagsTagIdRouteWithChildren
}

const ApiKoboTokenV1LibraryTagsRouteChildren: ApiKoboTokenV1LibraryTagsRouteChildren =
  {
    ApiKoboTokenV1LibraryTagsTagIdRoute:
      ApiKoboTokenV1LibraryTagsTagIdRouteWithChildren,
  }

const ApiKoboTokenV1LibraryTagsRouteWithChildren =
  ApiKoboTokenV1LibraryTagsRoute._addFileChildren(
    ApiKoboTokenV1LibraryTagsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  RegisterRoute: RegisterRoute,
  ShelvesRoute: ShelvesRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AuthorNameRoute: AuthorNameRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  SettingsKoboRoute: SettingsKoboRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  BooksBookIdEditRoute: BooksBookIdEditRoute,
  ApiBooksBookIdCoverRoute: ApiBooksBookIdCoverRoute,
  ApiBooksBookIdFilesFileIdRoute: ApiBooksBookIdFilesFileIdRoute,
  ApiKoboTokenV1SplatRoute: ApiKoboTokenV1SplatRoute,
  ApiKoboTokenV1InitializationRoute: ApiKoboTokenV1InitializationRoute,
  ApiKoboTokenDownloadBookIdBookFormatRoute:
    ApiKoboTokenDownloadBookIdBookFormatRoute,
  ApiKoboTokenV1AuthDeviceRoute: ApiKoboTokenV1AuthDeviceRoute,
  ApiKoboTokenV1AuthRefreshRoute: ApiKoboTokenV1AuthRefreshRoute,
  ApiKoboTokenV1LibraryBookUuidRoute: ApiKoboTokenV1LibraryBookUuidRoute,
  ApiKoboTokenV1LibrarySyncRoute: ApiKoboTokenV1LibrarySyncRoute,
  ApiKoboTokenV1LibraryTagsRoute: ApiKoboTokenV1LibraryTagsRouteWithChildren,
  ApiKoboTokenV1LibraryIdsMetadataRoute: ApiKoboTokenV1LibraryIdsMetadataRoute,
  ApiKoboTokenV1LibraryIdsStateRoute: ApiKoboTokenV1LibraryIdsStateRoute,
  ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRoute:
    ApiKoboTokenImageIdWidthHeightIsGreyscaleImageDotjpgRoute,
  ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRoute:
    ApiKoboTokenImageIdWidthHeightQualityIsGreyscaleImageDotjpgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
