/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as BooksBookIdEditRouteImport } from './routes/books.$bookId_.edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBooksBookIdCoverRouteImport } from './routes/api/books/$bookId/cover'
import { Route as ApiBooksBookIdFilesFileIdRouteImport } from './routes/api/books/$bookId/files/$fileId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdEditRoute = BooksBookIdEditRouteImport.update({
  id: '/books/$bookId_/edit',
  path: '/books/$bookId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksBookIdCoverRoute = ApiBooksBookIdCoverRouteImport.update({
  id: '/api/books/$bookId/cover',
  path: '/api/books/$bookId/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBooksBookIdFilesFileIdRoute =
  ApiBooksBookIdFilesFileIdRouteImport.update({
    id: '/api/books/$bookId/files/$fileId',
    path: '/api/books/$bookId/files/$fileId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/api/books/$bookId/cover': typeof ApiBooksBookIdCoverRoute
  '/api/books/$bookId/files/$fileId': typeof ApiBooksBookIdFilesFileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/api/books/$bookId/cover': typeof ApiBooksBookIdCoverRoute
  '/api/books/$bookId/files/$fileId': typeof ApiBooksBookIdFilesFileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/books/$bookId_/edit': typeof BooksBookIdEditRoute
  '/api/books/$bookId/cover': typeof ApiBooksBookIdCoverRoute
  '/api/books/$bookId/files/$fileId': typeof ApiBooksBookIdFilesFileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/books/$bookId'
    | '/api/auth/$'
    | '/books/$bookId/edit'
    | '/api/books/$bookId/cover'
    | '/api/books/$bookId/files/$fileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/books/$bookId'
    | '/api/auth/$'
    | '/books/$bookId/edit'
    | '/api/books/$bookId/cover'
    | '/api/books/$bookId/files/$fileId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/register'
    | '/books/$bookId'
    | '/api/auth/$'
    | '/books/$bookId_/edit'
    | '/api/books/$bookId/cover'
    | '/api/books/$bookId/files/$fileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  BooksBookIdEditRoute: typeof BooksBookIdEditRoute
  ApiBooksBookIdCoverRoute: typeof ApiBooksBookIdCoverRoute
  ApiBooksBookIdFilesFileIdRoute: typeof ApiBooksBookIdFilesFileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId_/edit': {
      id: '/books/$bookId_/edit'
      path: '/books/$bookId/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof BooksBookIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$bookId/cover': {
      id: '/api/books/$bookId/cover'
      path: '/api/books/$bookId/cover'
      fullPath: '/api/books/$bookId/cover'
      preLoaderRoute: typeof ApiBooksBookIdCoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/books/$bookId/files/$fileId': {
      id: '/api/books/$bookId/files/$fileId'
      path: '/api/books/$bookId/files/$fileId'
      fullPath: '/api/books/$bookId/files/$fileId'
      preLoaderRoute: typeof ApiBooksBookIdFilesFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  BooksBookIdEditRoute: BooksBookIdEditRoute,
  ApiBooksBookIdCoverRoute: ApiBooksBookIdCoverRoute,
  ApiBooksBookIdFilesFileIdRoute: ApiBooksBookIdFilesFileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
